name: Deploy EC2
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{secrets.SSH_KEY}}
          # name: Vitalii.pem
          known_hosts: ${{secrets.KNOWN_HOSTS}}
          if_key_exists: ignore      
      - name: rsync over ssh
        run: ./deploy_to_aws.sh
